Harim2da/share-diary

build.gradle
Mapstruct 설정 추가
* Exception 관련 빌드 에러 나는 부분은 우선 무시하고 올립니다.
=> [신규] Mapstruct 설정 추가

src/main/java/share_diary/diray/dailyDiary/domain/DailyDiary.java, src/main/java/share_diary/diray/diaryRoom/DiaryRoom.java, src/main/java/share_diary/diray/memberInviteHistory/domain/InviteAcceptStatus.java, src/main/java/share_diary/diray/memberInviteHistory/domain/MemberInviteHistory.java
일기, 일기방, 멤버 초대 관련 엔티티 1차 설계 건입니다.
연관관계 매핑, 추가로 논의 필요한 부분은 제외하고 작업했습니다.
=> [신규] 일기, 일기방, 멤버 초대 관련 엔티티 1차 설계

src/main/java/share_diary/diray/auth/AuthController.java, src/main/java/share_diary/diray/auth/AuthService.java
feat() : 230523 accessToken 만료시 개발급 API 개발
=> feat() : 230523 accessToken 만료시 개발급 API 개발

http/member.http, src/main/java/share_diary/diray/exception/member/PasswordNotCoincide.java, src/main/java/share_diary/diray/exception/response/ErrorType.java, src/main/java/share_diary/diray/member/MemberController.java, src/main/java/share_diary/diray/member/MemberService.java, src/main/java/share_diary/diray/member/domain/Member.java, src/main/java/share_diary/diray/member/dto/request/MemberSignUpRequestDTO.java, src/main/java/share_diary/diray/member/dto/request/MemberUpdateRequestDTO.java, src/test/java/share_diary/diray/member/MemberControllerTest.java
- 회원 수정 API
- 회원 수정 API TEST CODE
- PasswordNotCoincide 예외 추가
=> feat() : 회원 수정 API 개발 + 비밀번호,비밀번호확인 불일치 exception 추가

http/member.http, src/main/java/share_diary/diray/crypto/PasswordEncoder.java, src/main/java/share_diary/diray/exception/member/UpdatePasswordNotCoincide.java, src/main/java/share_diary/diray/exception/response/ErrorType.java, src/main/java/share_diary/diray/member/MemberController.java, src/main/java/share_diary/diray/member/MemberService.java, src/main/java/share_diary/diray/member/dto/request/MemberPasswordRequestDTO.java, src/test/java/share_diary/diray/member/MemberControllerTest.java
=> feat() : 회원 정보수정 전 비밀번호 확인 API 추가

src/main/java/share_diary/diray/dailyDiary/domain/DailyDiary.java, src/main/java/share_diary/diray/emoji/domain/Emoji.java, src/main/java/share_diary/diray/member/domain/Member.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/MemberDiaryRoom.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/Role.java
1. MemberDiaryRoom 에 권한컬럼을 추가하였습니다.
- Role Enum 을 생성하였습니다. 
- 소스 : Role.java
2. 연관관계를 정의해주었습니다.
- 소스 : DailyDiary, Emoji, Member, MemberDiaryRoom
3. 연관관계 편의 메소드를 추가하였습니다.
- Emoji, MemberDiaryRoom
*이상 있으시면 말씀해주세요!
=> feat() : Role enum 추가 + 연관관계 설정 및 편의메소드 추가

http/member.http, src/main/java/share_diary/diray/auth/AuthController.java, src/main/java/share_diary/diray/auth/domain/AuthenticationPrincipal.java, src/main/java/share_diary/diray/auth/domain/LoginSession.java, src/main/java/share_diary/diray/auth/dto/request/LoginRequestDTO.java, src/main/java/share_diary/diray/config/AuthenticationPrincipalArgumentResolver.java, src/main/java/share_diary/diray/config/WebMvcConfig.java, src/main/java/share_diary/diray/diaryRoom/DiaryRoom.java, src/main/java/share_diary/diray/member/MemberController.java, src/main/java/share_diary/diray/member/MemberService.java, src/main/java/share_diary/diray/member/domain/Role.java, src/main/java/share_diary/diray/member/dto/request/MemberPasswordRequestDTO.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/MemberDiaryRoom.java, src/test/java/share_diary/diray/member/MemberControllerTest.java
- AuthenticationPrincipalArgumentResolver 를 생성하였습니다
- accessToken 의 claim 에서 pk 값을 추출한뒤 api 현재 요청한 유저의 정보가 담겨있는 객체를 바인딩 해주었습니다.
-
=> feat() : ArgumentResolver 생성

src/test/java/share_diary/diray/auth/AuthControllerTest.java
- AuthController test code template 작성
=> feat() : AuthController test code template 작성

src/main/reactjs/src/atom/recoil.ts, src/main/reactjs/src/component/Calender/SelectedDiary.tsx, src/main/reactjs/src/component/Calender/ShareCalender.tsx, src/main/reactjs/src/component/CombineMenu/CombineMenu.tsx, src/main/reactjs/src/component/CombineMenu/Header.tsx, src/main/reactjs/src/component/CombineMenu/MenuList.tsx, src/main/reactjs/src/component/Common/ResetRecoil.tsx, src/main/reactjs/src/styles/ComponentsWrapper.tsx, src/main/reactjs/src/view/Main.tsx
사이드 메뉴 슬라이드 형식으로 수정, 반응형 추가 재작업
=> 사이드 메뉴 슬라이드 형식으로 수정, 반응형 추가

build.gradle, http/auth.http, src/main/java/share_diary/diray/auth/AuthController.java, src/main/java/share_diary/diray/auth/AuthService.java, src/main/java/share_diary/diray/auth/domain/token/AccessToken.java, src/main/java/share_diary/diray/auth/domain/token/RefreshToken.java, src/main/java/share_diary/diray/auth/domain/token/TokenRepository.java, src/main/java/share_diary/diray/auth/dto/request/LoginRequestDTO.java, src/main/java/share_diary/diray/config/WebMvcConfig.java, src/main/java/share_diary/diray/exception/GlobalExceptionController.java, src/main/java/share_diary/diray/exception/response/ErrorResponse.java, src/main/java/share_diary/diray/infrastructure/AuthInterceptor.java, src/main/java/share_diary/diray/infrastructure/AuthenticationPrincipalArgumentResolver.java, src/main/resources/application.yml
- logout API 개발하였습니다.
- Redis in-memory 설정을 세팅하였습니다.
- 로그인시에 refreshToken 을 redis memory 에 저장하였고, 정상적으로 조회까지 확인하였습니다.
=> feat() : logout API 개발 + Redis 설정 RefreshToken Redis memory 적용

http/auth.http, src/main/java/share_diary/diray/auth/AuthController.java, src/main/java/share_diary/diray/auth/AuthService.java
- 로그아웃 시에 redis 에서 refreshToken 제거
=> feat() : 로그아웃 시에 redis 에서 refreshToken 제거

build.gradle, src/main/java/share_diary/diray/auth/AuthController.java, src/main/java/share_diary/diray/auth/AuthService.java, src/main/java/share_diary/diray/auth/domain/token/RefreshTokenDB.java, src/main/java/share_diary/diray/auth/domain/token/TokenDbRepository.java
=> feat() : refreshToken DB 에 저장

src/main/java/share_diary/diray/member/MemberController.java
- 회원가입 url 변경
- /api/member/signUp
=> fix() : 회원가입 url 변경

src/main/java/share_diary/diray/diaryRoom/DiaryRoomService.java, src/main/java/share_diary/diray/exception/memberInviteHistory/InvalidInviteHistoryIdException.java, src/main/java/share_diary/diray/exception/response/ErrorType.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/MemberDiaryRoom.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/MemberDiaryRoomRepository.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/MemberDiaryRoomRepositoryCustom.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/impl/MemberDiaryRoomRepositoryCustomImpl.java, src/main/java/share_diary/diray/memberDiaryRoom/event/listener/InviteAcceptEventListener.java, src/main/java/share_diary/diray/memberDiaryRoom/event/listener/impl/InviteAcceptEventListenerImpl.java, src/main/java/share_diary/diray/memberInviteHistory/MemberInviteHistoryService.java, src/main/java/share_diary/diray/memberInviteHistory/controller/MemberInviteHistoryController.java, src/main/java/share_diary/diray/memberInviteHistory/controller/request/InviteUpdateRequest.java, src/main/java/share_diary/diray/memberInviteHistory/domain/MemberInviteHistory.java, src/main/java/share_diary/diray/memberInviteHistory/domain/MemberInviteHistoryRepositoryCustom.java, src/main/java/share_diary/diray/memberInviteHistory/domain/impl/MemberInviteHistoryRepositoryCustomImpl.java, src/main/java/share_diary/diray/memberInviteHistory/event/InviteAcceptEvent.java
일기방 초대에 대해  수락 혹은 거절에 대한 API입니다.
=> [신규] 일기방 초대 수락, 거절

http/auth.http, http/member.http, src/main/java/share_diary/diray/auth/AuthController.java, src/main/java/share_diary/diray/auth/AuthService.java, src/main/java/share_diary/diray/auth/dto/request/LoginRequestDTO.java, src/main/java/share_diary/diray/auth/oauth/GithubOAuthManager.java, src/main/java/share_diary/diray/auth/oauth/OAuthManager.java, src/main/java/share_diary/diray/auth/oauth/OAuthManagerFinder.java, src/main/java/share_diary/diray/auth/oauth/SocialType.java, src/main/java/share_diary/diray/auth/oauth/token/GithubTokenRequest.java, src/main/java/share_diary/diray/auth/oauth/token/GithubTokenResponse.java, src/main/java/share_diary/diray/auth/oauth/userInfo/GithubUserInfoResponse.java, src/main/java/share_diary/diray/auth/oauth/userInfo/OAuthUserInfoResponse.java, src/main/java/share_diary/diray/common/dto/EmptyJsonDTO.java, src/main/java/share_diary/diray/common/utils/StringUtil.java, src/main/java/share_diary/diray/config/RestTemplateConfig.java, src/main/java/share_diary/diray/infrastructure/AuthInterceptor.java, src/main/java/share_diary/diray/member/MemberController.java, src/main/java/share_diary/diray/member/MemberService.java, src/main/java/share_diary/diray/member/dto/request/MemberSignUpSocialRequestDTO.java, src/main/resources/application-local.yml, src/main/resources/application-secret.yml, src/main/resources/application.yml, src/test/java/share_diary/diray/auth/AuthControllerTest.java, src/test/resources/application-secret.yml, src/test/resources/application-test.yml
- code review 부탁드립니다!!!
- 빠르게 찾으실 수 있게 review 라는 키워드로 주석처리 해놓았습니다!!!
=> feat() : application file 재정의 + OAuth 구현

src/main/reactjs/src/atom/loginState.ts, src/main/reactjs/src/component/CombineMenu/Header.tsx, src/main/reactjs/src/view/Login.tsx, src/main/reactjs/src/view/SignUp.tsx
feat() : 회원가입/아이디 중복체크/로그인/로그아웃 구현
=> feat() : 회원가입/아이디 중복체크/로그인/로그아웃 구현

src/main/java/share_diary/diray/diaryRoom/DiaryRoom.java, src/main/java/share_diary/diray/diaryRoom/DiaryRoomService.java, src/main/java/share_diary/diray/diaryRoom/controller/DiaryRoomController.java, src/main/java/share_diary/diray/diaryRoom/controller/request/DiaryRoomCreateRequest.java, src/main/java/share_diary/diray/diaryRoom/event/DiaryRoomCreateEvent.java, src/main/java/share_diary/diray/member/MemberController.java, src/main/java/share_diary/diray/member/MemberService.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/MemberDiaryRoom.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/MemberDiaryRoomRepositoryCustom.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/impl/MemberDiaryRoomRepositoryCustomImpl.java, src/main/java/share_diary/diray/memberInviteHistory/MemberInviteRequest.java, src/main/java/share_diary/diray/memberInviteHistory/event/listener/DiaryRoomCreateEventListener.java, src/main/java/share_diary/diray/memberInviteHistory/event/listener/impl/DiaryRoomCreateEventListenerImpl.java
총 2개의 API입니다.
1) 해당 계정이 일기방 만들 수 있는지 체크 API
2) (가능하다면) 일기방 만드는 API
=> [B] 해당 계정이 일기방 만들 수 있는지 체크 API, 일기방 만드는 API

http/member.http, src/main/java/share_diary/diray/auth/AuthController.java, src/main/java/share_diary/diray/auth/AuthService.java, src/main/java/share_diary/diray/auth/oauth/token/GithubTokenResponse.java, src/main/java/share_diary/diray/common/email/CertificationNumber.java, src/main/java/share_diary/diray/common/email/CertificationNumberRepository.java, src/main/java/share_diary/diray/common/email/EmailSenderComponent.java, src/main/java/share_diary/diray/exception/certification/CertificationNotFoundException.java, src/main/java/share_diary/diray/exception/response/ErrorType.java, src/main/java/share_diary/diray/jwt/JwtManager.java, src/main/java/share_diary/diray/member/MemberController.java, src/main/java/share_diary/diray/member/MemberService.java, src/main/java/share_diary/diray/member/domain/Member.java, src/main/java/share_diary/diray/member/dto/request/MemberCertificationNumber.java
=> 로그인 로직 수정 + 비밀번호 변경 로직 추가

src/main/reactjs/src/component/FindMyInfo/EmailAuth.tsx
=> 아이디 찾기 api url 수정 - 선영

src/main/java/share_diary/diray/member/domain/JoinStatus.java, src/main/java/share_diary/diray/member/domain/Member.java, src/main/resources/application-local.yml
- joinStatus 를 Enum type 으로 변경하였습니다.
- application-local.yml 을 변경하였습니다
- H2 database 설정을 in-memory db 로 변경하였습니다
=> joinStatus 변경 + application.yml 변경

http/auth.http, src/main/java/share_diary/diray/member/MemberController.java, src/main/java/share_diary/diray/member/MemberService.java, src/main/java/share_diary/diray/member/domain/Member.java, src/main/java/share_diary/diray/member/dto/request/MemberEmailRequestDTO.java, src/main/java/share_diary/diray/member/dto/request/MemberPasswordRequestDTO.java, src/main/java/share_diary/diray/member/dto/request/MemberPasswordUpdateDTO.java
- 비밀번호 변경 api
- request DTO @Valid message 수정
- .http 파일 수정 ( 비밀번호 변경 추가 )
=> [B] 비밀번호 변경 api 개발 및 @Valid message 수정

src/main/java/share_diary/diray/auth/oauth/GoogleOAuthManager.java, src/main/java/share_diary/diray/auth/oauth/token/GoogleTokenRequest.java, src/main/java/share_diary/diray/auth/oauth/token/GoogleTokenResponse.java, src/main/java/share_diary/diray/auth/oauth/userInfo/GoogleUserInfoResponse.java, src/main/java/share_diary/diray/member/MemberController.java, src/main/resources/application-local.yml
- 임시비밀번호 api 삭제
- google oauth social login 기능 구현
=> [B] 임시비밀번호 api 삭제 + google social login 구현

src/main/resources/application-local.yml
- h2 console enabled true 설정
- application-local.yml 수정
=> feat() : h2 console enabled true 설정

src/main/resources/application-local.yml
config.activate.on-profile 누락
- local profile 추가
=> fix() : config.activate.on-profile 누락

http/member.http, src/main/java/share_diary/diray/member/MemberController.java, src/main/java/share_diary/diray/member/MemberService.java, src/main/java/share_diary/diray/member/dto/response/MemberMyPageDTO.java, src/test/java/share_diary/diray/member/MemberServiceTest.java
- myPage API 개발
- service test code 작성
=> feat() : myPage API 개발

src/main/java/share_diary/diray/common/email/EmailSenderComponent.java, src/main/java/share_diary/diray/diaryRoom/DiaryRoomService.java, src/main/java/share_diary/diray/diaryRoom/controller/DiaryRoomController.java, src/main/java/share_diary/diray/diaryRoom/event/DiaryRoomCreateEvent.java, src/main/java/share_diary/diray/memberInviteHistory/MemberInviteHistoryService.java, src/main/java/share_diary/diray/memberInviteHistory/MemberInviteRequest.java, src/main/java/share_diary/diray/memberInviteHistory/controller/MemberInviteHistoryController.java, src/main/java/share_diary/diray/memberInviteHistory/domain/MemberInviteHistory.java, src/main/java/share_diary/diray/memberInviteHistory/event/listener/impl/DiaryRoomCreateEventListenerImpl.java
일기방 초대 관련 host 추가, 초대 메일 발송 시 host nickname 추가 등
=> [수정] 일기방 초대 관련 host 추가, 초대 메일 발송 시 host nickname 추가 등

src/main/java/share_diary/diray/dailyDiary/domain/DailyDiary.java, src/main/java/share_diary/diray/dailyDiary/domain/MyEmoji.java, src/main/java/share_diary/diray/emoji/EmojiController.java, src/main/java/share_diary/diray/emoji/EmojiService.java, src/main/java/share_diary/diray/emoji/domain/Emoji.java, src/main/java/share_diary/diray/emoji/domain/MyEmoji.java, src/main/java/share_diary/diray/emoji/dto/request/DiaryEmojiRequest.java, src/test/java/share_diary/diray/diaryRoom/DiaryRoomApiTest.java, src/test/java/share_diary/diray/emoji/EmojiApiTest.java, src/test/java/share_diary/diray/member/MemberApiTest.java, src/test/java/share_diary/diray/member/MemberSteps.java, src/test/java/share_diary/diray/memberInviteHistory/MemberInviteHistoryApiTest.java
=> [B] 내 일기 감정 이모지 일기 entity 로 이전

http/member.http, src/main/java/share_diary/diray/common/BaseTimeEntity.java, src/main/java/share_diary/diray/common/LoginAuditingAware.java, src/main/java/share_diary/diray/emoji/EmojiController.java, src/main/java/share_diary/diray/emoji/EmojiService.java, src/main/java/share_diary/diray/emoji/domain/Emoji.java, src/main/java/share_diary/diray/memberInviteHistory/MemberInviteHistoryService.java, src/main/java/share_diary/diray/memberInviteHistory/dto/MemberInviteHistoryDTO.java, src/main/java/share_diary/diray/memberInviteHistory/mapper/MemberInviteHistoryMapper.java, src/test/java/share_diary/diray/memberInviteHistory/MemberInviteHistoryApiTest.java, src/test/java/share_diary/diray/memberInviteHistory/MemberInvitesHistorySteps.java
=> feat() : emoji 클릭시 api 틀 정의

src/main/java/share_diary/diray/member/MemberService.java, src/main/java/share_diary/diray/member/dto/request/MemberSignUpRequestDTO.java
- early return 수정
- 빵속빵 구조로 변경
=> feat() : 코드 리팩토링

src/main/java/share_diary/diray/dailyDiary/DailyDiaryRepository.java, src/main/java/share_diary/diray/dailyDiary/DailyDiaryRepositoryCustom.java, src/main/java/share_diary/diray/dailyDiary/DailyDiaryService.java, src/main/java/share_diary/diray/dailyDiary/controller/DailyDiaryController.java, src/main/java/share_diary/diray/dailyDiary/controller/request/DailyDiaryCreateModifyRequest.java, src/main/java/share_diary/diray/dailyDiary/domain/DailyDiary.java, src/main/java/share_diary/diray/dailyDiary/dto/DailyDiaryDTO.java, src/main/java/share_diary/diray/dailyDiary/impl/DailyDiaryRepositoryCustomImpl.java, src/main/java/share_diary/diray/dailyDiary/mapper/DailyDiaryMapper.java, src/main/java/share_diary/diray/exception/dailyDiary/InvalidRequestException.java, src/main/java/share_diary/diray/exception/http/ForbiddenException.java, src/main/java/share_diary/diray/exception/response/ErrorType.java
=> [B] 내 일기 수정 API 개발

src/main/java/share_diary/diray/diaryRoom/DiaryRoomService.java, src/main/java/share_diary/diray/diaryRoom/controller/DiaryRoomController.java, src/main/java/share_diary/diray/diaryRoom/controller/response/DiaryRoomMembersResponse.java, src/main/java/share_diary/diray/member/dto/MemberDTO.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/MemberDiaryRoom.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/MemberDiaryRoomRepositoryCustom.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/impl/MemberDiaryRoomRepositoryCustomImpl.java
특정 일자에 일기방에 속한 멤버 조회 API 개발 건입니다.
=> [B] 특정 일자에 일기방에 속한 멤버 조회

src/test/java/share_diary/diray/member/MemberApiTest.java
=> feat() : myPage 조회 api test code 작성

src/main/java/share_diary/diray/dailyDiary/DailyDiaryRepositoryCustom.java, src/main/java/share_diary/diray/dailyDiary/DailyDiaryService.java, src/main/java/share_diary/diray/dailyDiary/controller/DailyDiaryController.java, src/main/java/share_diary/diray/dailyDiary/impl/DailyDiaryRepositoryCustomImpl.java, src/main/java/share_diary/diray/exception/dailyDiary/InvalidGetDiaryException.java, src/main/java/share_diary/diray/exception/dailyDiary/TooManyDailyDiariesException.java, src/main/java/share_diary/diray/exception/http/InternalServerException.java, src/main/java/share_diary/diray/exception/response/ErrorType.java
=> [B] 선택한 날짜의 일기 조회

src/main/java/share_diary/diray/config/WebMvcConfig.java
- put/patch/delete http method 에 대해서 cors allow method 조건 추가
=> feat() : put/patch/delete http method 에 대해서 cors allow method 조건 추가

src/main/java/share_diary/diray/memberInviteHistory/controller/MemberInviteHistoryController.java, src/main/java/share_diary/diray/memberInviteHistory/dto/MemberInviteHistoryDTO.java, src/main/java/share_diary/diray/memberInviteHistory/mapper/MemberInviteHistoryMapper.java, src/test/java/share_diary/diray/memberInviteHistory/MemberInviteHistoryApiTest.java
=> feat() : 일기방 제목 ì 컬럼 추가

src/main/java/share_diary/diray/diaryRoom/DiaryRoomService.java, src/main/java/share_diary/diray/diaryRoom/controller/DiaryRoomController.java, src/main/java/share_diary/diray/exception/memberDiaryRoom/AlreadyExitedDiaryRoomException.java, src/main/java/share_diary/diray/exception/response/ErrorType.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/MemberDiaryRoom.java
=> [신규] 내가 속한 일기방 탈퇴

http/DailyDiary.http, src/main/java/share_diary/diray/member/MemberController.java, src/main/java/share_diary/diray/member/MemberService.java, src/main/java/share_diary/diray/member/domain/Member.java, src/main/java/share_diary/diray/member/domain/MemberRepositoryCustom.java, src/main/java/share_diary/diray/member/domain/impl/MemberRepositoryCustomImpl.java, src/main/java/share_diary/diray/member/dto/request/MemberSignUpRequestDTO.java, src/test/java/share_diary/diray/member/MemberServiceTest.java
- DailyDairy.http 파일 생성
- 일기방에 초대된 빈객체 회원가입 진행 시 이메일 체킹 로직 변경
=> DailyDairy.http 파일 생성 및 일기방에 초대된 빈객체 회원가입 진행 시 이메일 체킹 로직 변경

src/main/java/share_diary/diray/diaryRoom/DiaryRoom.java, src/main/java/share_diary/diray/diaryRoom/DiaryRoomRepositoryCustom.java, src/main/java/share_diary/diray/diaryRoom/DiaryRoomService.java, src/main/java/share_diary/diray/diaryRoom/controller/DiaryRoomController.java, src/main/java/share_diary/diray/diaryRoom/impl/DiaryRoomRepositoryCustomImpl.java, src/test/java/share_diary/diray/diaryRoom/DiaryRoomServiceTest.java, src/test/java/share_diary/diray/member/MemberServiceTest.java
=> feat() : 일기방 무한 스크롤 방식으로 조회 기능 추가

src/main/java/share_diary/diray/dailyDiary/DailyDiaryService.java, src/main/java/share_diary/diray/diaryRoom/DiaryRoomService.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/MemberDiaryRoomRepositoryCustom.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/impl/MemberDiaryRoomRepositoryCustomImpl.java
내가 속한 일기방 멤버 조회 쿼리 수정 및 관련 API 수정
=> [수정] 내가 속한 일기방 멤버 조회 쿼리 수정 및 관련 API 수정

src/main/java/share_diary/diray/auth/AuthInterceptor.java
- access token 만료시에 TokenExpiredException 응답
=> feat() : 20240110 access token 만료시에 TokenExpiredException 응답

src/main/java/share_diary/diray/dailyDiary/controller/DailyDiaryController.java, src/main/java/share_diary/diray/diaryRoom/DiaryRoomService.java, src/main/java/share_diary/diray/diaryRoom/controller/DiaryRoomController.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/MemberDiaryRoom.java
기획 변경으로 인한 일기방 탈퇴 로직 수정 및 불필요 API 제거
=> [수정] 기획 변경으로 인한 일기방 탈퇴 로직 수정 및 불필요 API 제거

src/main/java/share_diary/diray/diaryRoom/DiaryRoomService.java, src/main/java/share_diary/diray/diaryRoom/controller/DiaryRoomController.java, src/main/java/share_diary/diray/diaryRoom/controller/request/DiaryRoomHostModifyRequest.java, src/main/java/share_diary/diray/memberDiaryRoom/domain/MemberDiaryRoom.java
일기방 host가 일기방 탈퇴 시, 다른 사람에게 host 넘기고 일기방 나가는 API
=> [신규] 일기방 host가 일기방 탈퇴 시, 다른 사람에게 host 넘기고 일기방 나가는 API
